apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: bank-account-service
  name: bank-account-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-account-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bank-account-service
    spec:
      containers:
      - image: carlosfls/bank-account-service:0.0.3-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: bank-account-service
        readinessProbe:
          httpGet:
            port: 8100
            path: /actuator/health/readiness
          livenessProbe:
            httpGet:
              port: 8100
              path: /actuator/health/liveness
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: bank-account-service
  name: bank-account-service
  namespace: default
spec:
  ports:
    - port: 8100
      protocol: TCP
      targetPort: 8100
  selector:
    app: bank-account-service
  sessionAffinity: None
  type: LoadBalancer
